stages:
  - test

sudo: false

os: linux

language: node_js
node_js:
  - "10.13.0"


cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

jobs:
  include:
  - stage: test
    name: "Lint"
    script:
    - yarn prestorybook
    - yarn lint
  - stage: test
    name: "Unit test"
    script:
      - yarn test:coverage