stages:
  - test

sudo: false

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  include:
  - os: osx
    osx_image: xcode9.4

env:
  global:
  - NODE_VERSION=stable

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - yarn prestorybook
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; yarn global add react-native-cli    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; yarn global add detox-cli           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew tap wix/brew                   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install applesimutils          ; fi

install: yarn install

jobs:
  include:
  - stage: test
    name: "Unit test"
    script:
      - npm install -g codeclimate-test-reporter
      - yarn test:coverage
    after_script:
      - bash <(curl -s https://codecov.io/bash)
      - CODECLIMATE_API_HOST=CODECLIMATE_API_HOST CODECLIMATE_REPO_TOKEN=CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov/lcov.inf
  - stage: test
    name: "E2E test"
    script:
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; detox build --configuration ios.sim.release    ; fi
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]];yarn cucumber --configuration ios.sim.release   ; fi