stages:
  - test

sudo: false
os: linux

language: node_js
node_js:
  - "10.13.0"

cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install

jobs:
  include:
  - stage: test
    script:
      - npm install -g codeclimate-test-reporter
      - yarn test:coverage
    after_script:
      - bash <(curl -s https://codecov.io/bash)
      - CODECLIMATE_API_HOST=CODECLIMATE_API_HOST CODECLIMATE_REPO_TOKEN=CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov/lcov.info